### ISSUE TITLE
dnsmasq error with latest commit 

### ISSUE THREAD

**Issue by pwFoo** [BBVA/kvm#4] opened 2016-10-04 17:47 UTC
After docker pull the current commit I get an error:

```
dnsmasq: bad dhcp-range at line 1 of /etc/dnsmasq.d/eth0.conf
```

**cat /etc/dnsmasq.d/eth0.conf** 

```
dhcp-range=,
dhcp-host=5a:bf:ec:52:d1:cb,,,infinite
dhcp-option=option:netmask,255.255.0.0
```

**Comment by methadata** [comment] 2016-10-04 20:36
Thanks for the report

Are you sure this issue is still happening? Last commit [(f482d54)](https://github.com/BBVA/kvm/commit/f482d54c57fc6a702a13b4d395950a986979b969) supposed to fix this issue.

The issue was detected some minutes after the former commit and was immediately fixed. During this time, docker hub had the buggy image for some minutes.

Anyway, please let me know if I can close the issue, or comfirm that the issue is still there.

**Comment by pwFoo** [comment] 2016-10-05 08:42
Pulled the latest image and tried it again. Bad dhcp-range still there:

```
dnsmasq: bad dhcp-range at line 1 of /etc/dnsmasq.d/eth0.conf
```

My docker run command:

```
docker run -p 5900:5900 -p 2222:22 -p 4444:4444 -td --name kvm --privileged -v /home/rancher/image.qcow2:/image/image.qcow2 -e AUTO_ATTACH=y bbvainnotech/kvm:latest
```

**Closed as completed** 2016-10-05 08:44 UTC
Labels: bug
